cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      accessKey: ${AWS_ACCESSKEY}
      secretKey: ${AWS_SECRETKEY}
      instanceProfile: true
    rds:
      image:
        dbInstanceIdentifier: image
        databaseName: image
        username: ${AWS_DB_USERNAME}
        password: ${AWS_DB_PASSWORD}