spring:
  profiles:
    active: @activeSpringProfile@
  jpa:
    show-sql: true
  jackson:
    serialization:
      WRITE_CHAR_ARRAYS_AS_JSON_ARRAYS: false
  data:
    rest:
      basePath: /api
      defaultMediaType: application/json
logging:
  level:
    be.ordina: 'DEBUG'
    #org.hibernate: 'ERROR'

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      accessKey: 'AKIAIQYXG7RGROCRCKGQ'
      secretKey: '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'
      instanceProfile: true
---
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-ordineo.cfapps.io/eureka/ #http://localhost:8761/eureka/ #
ribbon:
  IsSecure: true
---
spring:
  profiles: hsql
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    data: classpath:/import-hsql.sql
    driverClassName: org.hsqldb.jdbc.JDBCDriver
---
spring:
  profiles: aws-rds
  datasource:
    driverClassName: com.mysql.jdbc.Driver
cloud:
  aws:
    rds:
      image:
        dbInstanceIdentifier: image
        databaseName: image
        username: admin
        password: image-admin
---
spring:
  profiles: cloud
server:
  port: ${PORT}
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    secureVirtualHostName: ${spring.application.name}
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
    nonSecurePort: 80
    nonSecurePortEnabled: false
    securePortEnabled: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${vcap.services.registry.credentials.url}
    healthcheck:
      enabled: true
